osx_image: xcode7.3
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
branches:
  only:
    - master
node:
  - "6"
  - "6.1"
cache:
    direcotries:
        - electron
        - node_modules
install:
  - npm install
script: npm test
