osx_image: xcode7.3
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node:
  - "6"
  - "6.1"
cache:
    direcotries:
        - electron
        - node_modules
install:
  - npm install -g npm@next
  - npm install -g webpack typescript tsd typings
  - npm install
  - typings install electron
script: npm run build
